#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load our dotfiles like ~/.aliases, etc…
for file in $HOME/.{aliases,zsh.local}; do
    [ -r "$file" ] && source "$file"
done
unset file
